name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

 jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Run ESLint
        run: eslint .

      - name: Run Prettier
        run: prettier --check "src/**/*.js"
     

